export const STORAGE_KEYS = {
  accounts: 'basketballAccounts',
  session: 'basketballSession',
  attendance: 'basketballAttendance',
  homework: 'basketballHomework',
  lessonRecords: 'basketballLessonRecords',
  lessonRecordVideos: 'basketballLessonRecordVideos',
  lessonRecordThumbnails: 'basketballLessonRecordThumbnails',
  dribbleCounts: 'basketballDribbleCountRecords',
  shotAttempts: 'shotAttemptRecords',
  shotSuccess: 'shotSuccessRecords',
  ballColors: 'basketballBallColors',
  ballBrand: 'basketballBallBrand',
  ballRecognitionProfile: 'basketballBallRecognitionProfile',
  ballRecognitionPreviews: 'basketballBallRecognitionPreviews',
  position: 'basketballPosition',
} as const;
